name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v2.0.1)'
        required: true
        default: 'v2.0.1'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Verify required files
      run: |
        echo Checking for required files...
        if exist "License.txt" (echo ✓ License.txt found) else (echo ✗ License.txt missing && exit /b 1)
        if exist "assets\icon.ico" (echo ✓ Icon file found) else (echo ✗ Icon file missing && exit /b 1)
        if exist "main.js" (echo ✓ main.js found) else (echo ✗ main.js missing && exit /b 1)
        if exist "package.json" (echo ✓ package.json found) else (echo ✗ package.json missing && exit /b 1)
      shell: cmd
        
    - name: Install dependencies
      run: npm ci
      
    - name: Show build configuration
      run: |
        echo === BUILD CONFIGURATION ===
        node --version
        npm --version
        echo Current directory:
        cd
        echo Directory contents:
        dir
      shell: cmd
      
    - name: Build application
      run: npm run dist
      shell: cmd
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: electron-builder
        
    - name: List build artifacts
      run: |
        echo Listing dist directory contents:
        dir dist /s
      shell: cmd
        
    - name: Release to GitHub (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      run: npm run release
      shell: cmd
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
        retention-days: 30

# Removed redundant create-release job - electron-builder handles GitHub releases when using npm run release 