name: Test Build (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Debug environment
      run: |
        echo === ENVIRONMENT DEBUG ===
        node --version
        npm --version
        echo Current directory:
        cd
        echo Directory contents:
        dir
      shell: cmd
        
    - name: Install dependencies
      run: |
        npm install
        dir node_modules
      shell: cmd
        
    - name: Test electron-builder without publishing
      run: npx electron-builder --publish=never --win --x64
      shell: cmd
      env:
        DEBUG: electron-builder
        NODE_ENV: production
        
    - name: List results
      run: |
        echo Build completed, checking results...
        dir dist /s
      shell: cmd 