name: Test Build (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Debug environment
      run: |
        echo "=== ENVIRONMENT DEBUG ==="
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(Get-Location)"
        echo "Directory contents:"
        Get-ChildItem | Format-Table Name, Length, LastWriteTime
        echo "Environment variables:"
        Get-ChildItem env: | Where-Object { $_.Name -like "*NODE*" -or $_.Name -like "*NPM*" } | Format-Table Name, Value
      shell: powershell
        
    - name: Install dependencies
      run: |
        echo Installing dependencies...
        npm install
        echo Dependencies installed successfully
        echo Checking node_modules...
        if exist "node_modules" (echo ✓ node_modules exists) else (echo ✗ node_modules missing)
        
    - name: Test electron-builder without publishing
      run: |
        echo Testing electron-builder build...
        echo Running: npx electron-builder --publish=never
        npx electron-builder --publish=never --win --x64
        echo Build test completed successfully
      env:
        DEBUG: electron-builder
        NODE_ENV: production
        
    - name: List results
      run: |
        echo Checking build results...
        if exist "dist" (
          echo ✓ dist directory exists
          dir dist /s
        ) else (
          echo ✗ dist directory missing
        ) 